services:
  backend:
    container_name: smooches-backend
    image: ejweiner/smooches-backend:1.0
    build:
      context: './backend'
      target: 'prod'
    restart: always
    env_file:
      - ./backend/.env.prod
  frontend:
    container_name: smooches-frontend
    build:
      context: './frontend'
      target: 'prod'
    depends_on:
      - backend
    image: ejweiner/smooches-frontend:1.0
    environment:
      - PORT=3000