services:
  backend:
    build:
      context: './backend'
      target: 'dev'
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=8080
    ports:
      - '8080:8080'
    working_dir: /opt/node-app
    volumes:
      - ./backend:/opt/node-app:cached
  frontend:
    build:
      context: './frontend'
      target: 'dev'
    command: sh -c "npm install && npm run start"
    working_dir: /opt/react-app
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/opt/react-app:cached